### ISSUE TITLE
Simple Keyboard example not working with Raspberry PI Pico W

### ISSUE THREAD

**Issue by Marcus11Dev** [Heerkog/MicroPythonBLEHID#17]
Hello there,

I am using a Raspberry Pi Pico W and want to use it as a keyboard. When I run the simple/keyboard_example.py example I get a timeout error: `Traceback (most recent call last):
  File "<stdin>", line 192, in <module>
  File "<stdin>", line 42, in __init__
  File "hid_services.py", line 902, in start
  File "hid_services.py", line 326, in start
OSError: [Errno 110] ETIMEDOUT` and I can't find the device when scanning for devices with my PC (Linux Mint) or iPhone (iOS 17.1.2). With some debugging I found out that the code never leaves the `self._ble.active(1)` call in the `start(self)` methode. The Micropython version used on the Pico is 1.21.0. 

Can anybode please help with this issue? And another question that came up for me: what the `keys.json` file is used for?

Thanks for any help.

**Comment by Heerkog** [comment]
Hi Marcus,

Thank you for your bug report.

Sadly, it's a known issue that the current implementation is not working with MicroPython versions 1.20 and up. Please see the other issues related to this issue. Since I'm unable to currently test myself, I'm unable to debug. Therefore, any help is definitely appreciated!

The keys file is used to save keys for bonded devices.

Thanks.
