### ISSUE TITLE
Mouse and keyboard?

### ISSUE THREAD

**Issue by aloneguid** [Heerkog/MicroPythonBLEHID#20]
Is it possible to act as a mouse and keyboard at the same time? I have managed to make it work exclusively as keyboard or exclusively as mouse, but not simultaneously. HID spec is hard to understand,  wondering if you can help please 🙏

**Comment by Heerkog** [comment]
Yes, but this functionality is not offered 'out of the box'. In order to have a mouse + keyboard, you will need to subclass HumanInterfaceDevice to create a device with service and report descriptors that support mouse and keyboard functionalities.

You can follow the same structure as the Keyboard class. The resources section of the readme has a good [tutorial](https://eleccelerator.com/tutorial-about-usb-hid-report-descriptors/) on how to create a descriptor for such a multi-device.

Once you have a multi-device descriptor, your input report should match the bytes for that descriptor.

**Comment by aloneguid** [comment]
Thank you, great tutorial by the way. I have managed to create keyboard and mouse running on pico now.

**Comment by Heerkog** [comment]
Excellent! A pull request with this functionality would probably be appreciated by many others!

**Comment by dahanzimin** [comment]
@aloneguid Thank you for your success. Would you be willing to share how to configure the keyboard and mouse to work together? Thank you

**Comment by minghao999** [comment]
I have tried many methods but cannot understand how keyboard and mouse work simultaneously. Can you share your example? Thank you.🙏
