### ISSUE TITLE
Can you do more than one thing

### ISSUE THREAD

**Issue by Github73840134** [Heerkog/MicroPythonBLEHID#3]
IE
Mouse+Keyboard?

**Comment by Heerkog** [comment]
Yes, but this functionality is not offered 'out of the box'. In order to have a mouse + keyboard, you will need to subclass HumanInterfaceDevice to create a device with service and report descriptors that support mouse and keyboard functionalities.

You can follow the same structure as the Keyboard class. The resources section of the readme has a good tutorial on how to create a descriptor for such a multidevice.
